cluster.name: elasticsearch-tests
network.host: 127.0.0.1
discovery:
  zen:
    multicast.enabled: false
node.local: true
index.store.type: memory
logger: 
  action: DEBUG
path:
  plugins: ./target/classes/
