rootLogger: DEBUG, console

logger:
  action: DEBUG
  org.elasticsearch.client.transport: DEBUG
  
appender:
  file:
    type: file
    file: ${path.logs}/${cluster.name}.log
    layout:
      type: pattern
      conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"

index_search_slow_log_file:
  type: dailyRollingFile
  file: ${path.logs}/${cluster.name}_index_search_slowlog.log
  datePattern: "'.'yyyy-MM-dd"
  layout:
    type: pattern
    conversionPattern: "[%d{ISO8601}][%-5p][%-25c] %m%n"